baseURL = "https://sudrizzz.github.com"
languageCode = "zh-cn"
title = "Anthony's Blog"
theme = "yinyang"
DefaultContentLanguage = "cn"

[author]
  name = "Anthony Qu"
  homepage = "https://github.com/sudrizzz/"

[languages]
  # [languages.en]
  #   contentDir = "content/en"
  #   languageName = "English"
  #   weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 1

[params]
disqus = "sudri" # disqus account name
extraHead = ''
mainSections = ["posts"]
# googleAnalytics = "UA-96156731-1"
# description = "这里是张思扬的博客，写些心得。更多的是吐槽与无理取闹。"

[[params.socials]]
name = "Github"
link = "https://github.com/sudrizzz/"

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "~"
link = "https://music.163.com/song?id=356827"